### ISSUE TITLE
Tests fail against Keycloak 8+

### ISSUE THREAD

**Issue by ath88** [keycloak/keycloak-nodejs-admin-client#113]
**Describe the bug**
The test suite fails with this error against Keycloak 8.0.2 and newer.
```
  1) Users
       should remove totp:
     Error: Request failed with status code 404
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:244:11)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**To Reproduce**
Check the logs here:
https://github.com/keycloak/keycloak-nodejs-admin-client/actions/runs/460584766

**Expected behavior**
The tests should pass

**Screenshots**
I posted the log above - should be sufficient

**Additional context**
Keycloak 9+ has the same issue, but there are additional failures. Lets tackle one at a time.

**Comment by ath88** [comment]
The latest update fixed support for Keycloak 8 with removal of the totp-endpoint. We should change the tests to not allow tests on Keycloak 8 to fail.

**Comment by ath88** [comment]
See #117. Closing this.
