### ISSUE TITLE
Test fails on Keycloak 9+

### ISSUE THREAD

**Issue by ath88** [keycloak/keycloak-nodejs-admin-client#118]
**Describe the bug**
The tests fail with this error:
```
  1) Users
       count users with filter:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Suite.<anonymous> (test/users.spec.ts:82:25)
      at step (test/users.spec.ts:52:23)
      at Object.next (test/users.spec.ts:33:53)
      at fulfilled (test/users.spec.ts:24:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

See https://github.com/keycloak/keycloak-nodejs-admin-client/actions/runs/463447567

**To Reproduce**
Spin up a Keycloak 9 for testing and run the tests-suite.

**Expected behavior**

**Screenshots**
See log verbatim above.

**Enviroment (please complete the following information):**
 - Keycloak Version 9
 - Library Version - master branch

**Additional context**
I have not looked into the actual error, but it also exists on Keycloak 10, 11 and 12.

**Comment by jonkoops** [comment]
This issue has been resolved.
